# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RealAppWKM' do

  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Storage', '~> 6.3.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealAppWKM

  target 'RealAppWKM-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealAppWKMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

